spring:
  datasource:
    url: ${MYSQL_ADDON_URL}
    username: ${MYSQL_ADDON_USER}
    password: ${MYSQL_ADDON_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
springdoc:
  api-docs:
    path: /api/docs
  swagger-ui:
    path:/api/docs/swagger-ui-custom.html
logging:
  level:
    ROOT: WARN
    com.mec.apportfoliobackend: DEBUG
